services:
  db:
    image: mysql:8.0
    container_name: gameflix-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gameflix_db
      MYSQL_ROOT_PASSWORD: sqlroot4158
      MYSQL_USER: gameflix
      MYSQL_PASSWORD: gameflixpass
    command: >
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -psqlroot4158 -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: gameflix-app
    depends_on:
      db:
        condition: service_healthy
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gameflix_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

      SPRING_DATASOURCE_USERNAME: gameflix
      SPRING_DATASOURCE_PASSWORD: gameflixpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  dbdata:
